AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Metrics/MethodLength:
  CountComments: true
  Max: 20

Lint/ScriptPermission:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

require:
  - rubocop-rake
  - rubocop-rspec